# Generated by Django 3.1.7 on 2021-03-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id_no',
            new_name='identityno',
        ),
    ]
