# Generated by Django 3.1.7 on 2021-05-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_bidder_chats_item_payment_returned_item_sold_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='message',
            field=models.CharField(default='My Message', max_length=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, upload_to='items/'),
        ),
    ]
