# Generated by Django 3.1.7 on 2021-05-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210514_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bidder',
            name='date_bid',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='returned_item',
            name='date_returned',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
