# Generated by Django 3.1.7 on 2021-05-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210517_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AddField(
            model_name='item',
            name='approval_status',
            field=models.CharField(default='Waiting', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='auction_status',
            field=models.CharField(default='Scheduled', max_length=50),
        ),
    ]
