# Generated by Django 3.1.7 on 2021-05-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='interested',
            name='pay_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profilepics'),
        ),
    ]
