# Generated by Django 3.1.7 on 2021-05-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210524_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interested',
            name='item',
        ),
        migrations.RemoveField(
            model_name='interested',
            name='pay_status',
        ),
        migrations.RemoveField(
            model_name='interested',
            name='user',
        ),
        migrations.AddField(
            model_name='interested',
            name='amount_paid',
            field=models.IntegerField(blank=True, default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interested',
            name='item_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='interested',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
